name: Delete Preview Namespace

on: 
  pull_request: 
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Login
      uses: okteto/login@main
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Delete namespace
      uses: okteto/delete-namespace@main
      with:
        namespace: pr-${{ github.event.number }}-kenmwaura1
